# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'hello'

require 'grpc'
require 'hello_pb'

module Hello
  module HelloService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'hello.HelloService'

      # This thing just says Hello to anyone
      # SayHello('Euler') -> Hello, Euler!
      rpc :SayHello, HelloReq, HelloResp
      # Strict Version responds only to requests which have `Name` length
      # less than 10 characters
      rpc :SayHelloStrict, HelloReq, HelloResp
    end

    Stub = Service.rpc_stub_class
  end
end
